server:
  port: 8120 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

#spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos服务地址

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com #你的endponit
    bucketname: it-guli #bucket可以在控制台创建，也可以使用java代码创建，注意先测试bucket是否已被占用
    accesskeyid: LTAI5tBAJdmCwx3Qqk2MwRf5 #你的阿里云accesskeyid
    accesskeysecret: 5W1uEo93lwCJ9psWCv7y8yOK8PBwVr #你的阿里云accesskeysecret